"""Add all missing columns

Revision ID: bc77de430bad
Revises: 
Create Date: 2026-02-18 11:08:53.656789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc77de430bad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_prompts_id'), table_name='survey_prompts')
    op.drop_table('survey_prompts')
    op.drop_index(op.f('ix_survey_files_id'), table_name='survey_files')
    op.drop_index(op.f('ix_survey_files_session_id'), table_name='survey_files')
    op.drop_table('survey_files')
    op.drop_index(op.f('ix_survey_conversations_id'), table_name='survey_conversations')
    op.drop_index(op.f('ix_survey_conversations_session_id'), table_name='survey_conversations')
    op.drop_table('survey_conversations')
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_session_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_session_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_connection_logs_id'), table_name='connection_logs')
    op.drop_index(op.f('ix_connection_logs_session_id'), table_name='connection_logs')
    op.drop_table('connection_logs')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('bot_response', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('connection_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('connection_quality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('connection_speed', sa.VARCHAR(length=50), nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latency', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_logs_session_id'), 'connection_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_connection_logs_id'), 'connection_logs', ['id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('position_applied', sa.VARCHAR(length=100), nullable=True),
    sa.Column('interview_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('passed_first_interview', sa.BOOLEAN(), nullable=True),
    sa.Column('interview_score', sa.INTEGER(), nullable=True),
    sa.Column('incorporation_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('education_level', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_interest_reason', sa.TEXT(), nullable=True),
    sa.Column('years_experience', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_job_info', sa.TEXT(), nullable=True),
    sa.Column('can_travel', sa.BOOLEAN(), nullable=True),
    sa.Column('knows_office', sa.BOOLEAN(), nullable=True),
    sa.Column('salary_agreement', sa.BOOLEAN(), nullable=True),
    sa.Column('schedule_availability', sa.TEXT(), nullable=True),
    sa.Column('accepts_polygraph', sa.BOOLEAN(), nullable=True),
    sa.Column('accepts_socioeconomic', sa.BOOLEAN(), nullable=True),
    sa.Column('accepts_drug_test', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_candidates_session_id'), 'candidates', ['session_id'], unique=1)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting_value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=1)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('candidate_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ip_city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip_region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip_country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip_postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ip_latitude', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ip_longitude', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ip_timezone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip_isp', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip_organization', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip_asn', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip_is_proxy', sa.BOOLEAN(), nullable=True),
    sa.Column('ip_is_mobile', sa.BOOLEAN(), nullable=True),
    sa.Column('browser_user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('browser_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('browser_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('browser_os', sa.VARCHAR(length=100), nullable=True),
    sa.Column('browser_platform', sa.VARCHAR(length=100), nullable=True),
    sa.Column('browser_language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('browser_languages', sa.VARCHAR(length=200), nullable=True),
    sa.Column('browser_timezone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('browser_timezone_offset', sa.INTEGER(), nullable=True),
    sa.Column('screen_width', sa.INTEGER(), nullable=True),
    sa.Column('screen_height', sa.INTEGER(), nullable=True),
    sa.Column('screen_avail_width', sa.INTEGER(), nullable=True),
    sa.Column('screen_avail_height', sa.INTEGER(), nullable=True),
    sa.Column('screen_color_depth', sa.INTEGER(), nullable=True),
    sa.Column('screen_pixel_depth', sa.INTEGER(), nullable=True),
    sa.Column('device_pixel_ratio', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cpu_cores', sa.INTEGER(), nullable=True),
    sa.Column('device_memory', sa.INTEGER(), nullable=True),
    sa.Column('max_touch_points', sa.INTEGER(), nullable=True),
    sa.Column('has_touch_support', sa.BOOLEAN(), nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('connection_downlink', sa.VARCHAR(length=50), nullable=True),
    sa.Column('connection_rtt', sa.INTEGER(), nullable=True),
    sa.Column('connection_effective_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('canvas_fingerprint', sa.VARCHAR(length=100), nullable=True),
    sa.Column('webgl_vendor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('webgl_renderer', sa.VARCHAR(length=200), nullable=True),
    sa.Column('do_not_track', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cookies_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('local_storage_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('session_storage_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('indexed_db_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('permissions_notifications', sa.VARCHAR(length=20), nullable=True),
    sa.Column('permissions_geolocation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('battery_charging', sa.BOOLEAN(), nullable=True),
    sa.Column('battery_level', sa.INTEGER(), nullable=True),
    sa.Column('plugins_list', sa.TEXT(), nullable=True),
    sa.Column('fonts_available', sa.TEXT(), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('full_address', sa.TEXT(), nullable=True),
    sa.Column('share_location', sa.BOOLEAN(), nullable=True),
    sa.Column('curp', sa.VARCHAR(length=18), nullable=True),
    sa.Column('nss_imss', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rfc_tax_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('utility_provider', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utility_contract_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utility_account_holder', sa.VARCHAR(length=100), nullable=True),
    sa.Column('housing_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lives_with', sa.TEXT(), nullable=True),
    sa.Column('dependents_count', sa.INTEGER(), nullable=True),
    sa.Column('has_water', sa.BOOLEAN(), nullable=True),
    sa.Column('has_electricity', sa.BOOLEAN(), nullable=True),
    sa.Column('has_internet', sa.BOOLEAN(), nullable=True),
    sa.Column('has_gas', sa.BOOLEAN(), nullable=True),
    sa.Column('real_estate', sa.TEXT(), nullable=True),
    sa.Column('vehicles', sa.TEXT(), nullable=True),
    sa.Column('businesses', sa.TEXT(), nullable=True),
    sa.Column('formal_savings', sa.TEXT(), nullable=True),
    sa.Column('debts', sa.TEXT(), nullable=True),
    sa.Column('credit_bureau', sa.VARCHAR(length=50), nullable=True),
    sa.Column('education_level', sa.VARCHAR(length=100), nullable=True),
    sa.Column('has_education_proof', sa.BOOLEAN(), nullable=True),
    sa.Column('position_applying', sa.VARCHAR(length=100), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('area_division', sa.VARCHAR(length=100), nullable=True),
    sa.Column('application_reason', sa.VARCHAR(length=100), nullable=True),
    sa.Column('how_found_vacancy', sa.TEXT(), nullable=True),
    sa.Column('current_employment', sa.TEXT(), nullable=True),
    sa.Column('previous_employment', sa.TEXT(), nullable=True),
    sa.Column('salary_bonus', sa.VARCHAR(length=100), nullable=True),
    sa.Column('family_support', sa.VARCHAR(length=100), nullable=True),
    sa.Column('informal_business_income', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expenses_list', sa.TEXT(), nullable=True),
    sa.Column('expenses_amounts', sa.TEXT(), nullable=True),
    sa.Column('groceries', sa.VARCHAR(length=50), nullable=True),
    sa.Column('alimony', sa.VARCHAR(length=50), nullable=True),
    sa.Column('food_out', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rent', sa.VARCHAR(length=50), nullable=True),
    sa.Column('utilities', sa.VARCHAR(length=50), nullable=True),
    sa.Column('internet_cable', sa.VARCHAR(length=50), nullable=True),
    sa.Column('transportation', sa.VARCHAR(length=50), nullable=True),
    sa.Column('uber_taxi', sa.VARCHAR(length=50), nullable=True),
    sa.Column('school_expenses', sa.VARCHAR(length=50), nullable=True),
    sa.Column('courses', sa.VARCHAR(length=50), nullable=True),
    sa.Column('books_supplies', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entertainment', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vacations', sa.VARCHAR(length=50), nullable=True),
    sa.Column('insurance', sa.VARCHAR(length=50), nullable=True),
    sa.Column('taxes', sa.VARCHAR(length=50), nullable=True),
    sa.Column('clothing', sa.VARCHAR(length=50), nullable=True),
    sa.Column('laundry', sa.VARCHAR(length=50), nullable=True),
    sa.Column('internet_expenses', sa.VARCHAR(length=50), nullable=True),
    sa.Column('has_medical_condition', sa.BOOLEAN(), nullable=True),
    sa.Column('takes_permanent_medication', sa.BOOLEAN(), nullable=True),
    sa.Column('primary_family_contacts', sa.TEXT(), nullable=True),
    sa.Column('secondary_family_contacts', sa.TEXT(), nullable=True),
    sa.Column('work_references', sa.TEXT(), nullable=True),
    sa.Column('personal_reference', sa.TEXT(), nullable=True),
    sa.Column('work_reference_1_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('work_reference_1_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('work_reference_1_relationship', sa.VARCHAR(length=100), nullable=True),
    sa.Column('work_reference_2_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('work_reference_2_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('work_reference_2_relationship', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sa.VARCHAR(length=50), nullable=True),
    sa.Column('partner_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('partner_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('partner_occupation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('partner_relationship_quality', sa.VARCHAR(length=100), nullable=True),
    sa.Column('children_names', sa.TEXT(), nullable=True),
    sa.Column('children_count', sa.INTEGER(), nullable=True),
    sa.Column('home_references', sa.TEXT(), nullable=True),
    sa.Column('crime_in_area', sa.VARCHAR(length=50), nullable=True),
    sa.Column('services_quality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('security_quality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('surveillance_quality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bedrooms', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dining_room', sa.VARCHAR(length=20), nullable=True),
    sa.Column('living_room', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bathrooms', sa.VARCHAR(length=20), nullable=True),
    sa.Column('floors', sa.VARCHAR(length=20), nullable=True),
    sa.Column('garden', sa.VARCHAR(length=20), nullable=True),
    sa.Column('kitchen', sa.VARCHAR(length=20), nullable=True),
    sa.Column('air_conditioning', sa.VARCHAR(length=20), nullable=True),
    sa.Column('garage', sa.VARCHAR(length=20), nullable=True),
    sa.Column('laundry_area', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pool', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sports_areas', sa.VARCHAR(length=20), nullable=True),
    sa.Column('study_office', sa.VARCHAR(length=20), nullable=True),
    sa.Column('has_federal_license', sa.BOOLEAN(), nullable=True),
    sa.Column('federal_license_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('medical_folio', sa.VARCHAR(length=100), nullable=True),
    sa.Column('license_validity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('license_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('has_state_license', sa.BOOLEAN(), nullable=True),
    sa.Column('state_license_info', sa.TEXT(), nullable=True),
    sa.Column('state_license_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state_license_validity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('facebook_profile_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('home_photos_submitted', sa.BOOLEAN(), nullable=True),
    sa.Column('street_photos_submitted', sa.BOOLEAN(), nullable=True),
    sa.Column('recommendation_letters_submitted', sa.BOOLEAN(), nullable=True),
    sa.Column('evidence_sent', sa.TEXT(), nullable=True),
    sa.Column('has_legal_issues', sa.BOOLEAN(), nullable=True),
    sa.Column('legal_issues_description', sa.TEXT(), nullable=True),
    sa.Column('survey_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('current_section', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_session_id'), 'survey_responses', ['session_id'], unique=1)
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    op.create_table('survey_conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('bot_response', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_conversations_session_id'), 'survey_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_survey_conversations_id'), 'survey_conversations', ['id'], unique=False)
    op.create_table('survey_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_files_session_id'), 'survey_files', ['session_id'], unique=False)
    op.create_index(op.f('ix_survey_files_id'), 'survey_files', ['id'], unique=False)
    op.create_table('survey_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('prompt_content', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_prompts_id'), 'survey_prompts', ['id'], unique=False)
    # ### end Alembic commands ###
